#!/usr/bin/env python3
"""One-time generator for src/stars.js — the boat-view star catalog.

Reads the Yale Bright Star Catalog (bsc5-short.json, checked in next to this
script; re-downloaded if missing), keeps every star to V <= 3.0 as anonymous
"field" points, and emits the Carolinian compass type-stars as named entries
whose `group` strings match the base star names used in ETAK_COMPASS
(src/passages.js), so the app can map star-house -> physical star(s).

Coordinates are J2000; the ~0.4 deg of precession since the 1970s voyages is
far below display resolution. Pure stdlib.

    python3 tools/build_stars.py
"""
import json
import math
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "bsc5-short.json")   # checked-in source data
OUT = os.path.join(HERE, "..", "src", "stars.js")
URL = ("https://raw.githubusercontent.com/brettonw/YaleBrightStarCatalog/"
       "master/bsc5-short.json")

MAG_LIMIT = 3.0

# HR -> (group, carolinian name or None, label_anchor). `group` must equal the
# base star string in ETAK_COMPASS (docs/sources.md §1); multi-star groups mark
# one anchor whose label is drawn.
COMPASS = {
    424:  ("Polaris",      "Fúsemakut",       True),   # α UMi
    5563: ("Kochab",       "Maylap-en-efeng", True),   # β UMi
    4301: ("Dubhe",        None,              True),   # α UMa
    168:  ("Cassiopeia",   "Úgúlúg",          True),   # Schedar, α Cas
    7001: ("Vega",         "Máán",            True),   # α Lyr
    1165: ("Pleiades",     "Maríger",         True),   # Alcyone, η Tau
    1457: ("Aldebaran",    "Úún",             True),   # α Tau
    7710: ("Tarazed",      None,              True),   # γ Aql
    7557: ("Altair",       "Máálap",          True),   # α Aql
    7602: ("Alshain",      None,              True),   # β Aql
    1852: ("Orion’s Belt", "Elúél",           False),  # Mintaka, δ Ori
    1903: ("Orion’s Belt", "Elúél",           True),   # Alnilam, ε Ori
    1948: ("Orion’s Belt", "Elúél",           False),  # Alnitak, ζ Ori
    4662: ("Corvus",       "Sárapúl",         True),   # Gienah, γ Crv
    6134: ("Antares",      "Túmur",           True),   # α Sco
    6527: ("Shaula",       "Mesáárú",         True),   # λ Sco
    4730: ("Crux",         "Wénéwén",         False),  # Acrux, α Cru
    4853: ("Crux",         "Wénéwén",         False),  # Mimosa, β Cru
    4763: ("Crux",         "Wénéwén",         True),   # Gacrux, γ Cru
    4656: ("Crux",         "Wénéwén",         False),  # δ Cru
    5459: ("Crux",         None,              False),  # α Cen (45° elevations)
}


def fetch():
    if not os.path.exists(CACHE):
        print(f"downloading {URL} ...", file=sys.stderr)
        with urllib.request.urlopen(URL) as r:
            data = r.read()
        with open(CACHE, "wb") as f:
            f.write(data)
    with open(CACHE) as f:
        return json.load(f)


def ra_deg(s):
    h, m, sec = re.match(r"(\d+)h (\d+)m ([\d.]+)s", s).groups()
    return (int(h) + int(m) / 60 + float(sec) / 3600) * 15


def dec_deg(s):
    sign, d, m, sec = re.match(r"([+-])(\d+)° (\d+)′ (\d+)″", s).groups()
    v = int(d) + int(m) / 60 + int(sec) / 3600
    return -v if sign == "-" else v


def main():
    field, compass = [], []
    for e in fetch():
        if "RA" not in e or "Dec" not in e or "V" not in e:
            continue
        hr = int(e["HR"])
        ra, dec, mag = ra_deg(e["RA"]), dec_deg(e["Dec"]), float(e["V"])
        if hr in COMPASS:
            group, car, anchor = COMPASS[hr]
            compass.append({"ra": round(ra, 2), "dec": round(dec, 2),
                            "mag": round(mag, 2), "name": e.get("N", group),
                            "car": car, "group": group, "lbl": 1 if anchor else 0})
        elif mag <= MAG_LIMIT:
            field.append([round(ra, 2), round(dec, 2), round(mag, 1)])

    missing = len(COMPASS) - len(compass)
    if missing:
        sys.exit(f"error: {missing} compass HR numbers not found in catalog")

    header = ("// GENERATED by tools/build_stars.py — do not edit by hand.\n"
              "// Yale Bright Star Catalog (J2000): field stars to V<=%.1f plus the\n"
              "// Carolinian compass type-stars (groups match ETAK_COMPASS).\n"
              % MAG_LIMIT)
    body = "const STAR_MAP = " + json.dumps(
        {"field": field, "compass": compass},
        separators=(",", ":"), ensure_ascii=False) + ";\n"
    body += ("if (typeof module !== 'undefined' && module.exports) "
             "module.exports = STAR_MAP;\n")
    with open(OUT, "w") as f:
        f.write(header + body)
    print(f"wrote {OUT}: {len(field)} field + {len(compass)} compass stars, "
          f"{os.path.getsize(OUT)/1024:.0f} KB", file=sys.stderr)


if __name__ == "__main__":
    main()
